//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CategoryCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryCustomer()
        {
            this.Customers = new HashSet<Customer>();
        }
        [NotMapped]
        public List<CategoryCustomer> ListCateCus { get; set; }
        [Display(Name = "Mã loại khách hàng: ")]
        [Required(ErrorMessage = "Mã loại khách hàng không được để trống ...")]
        public string IDCateCus { get; set; }
        [Display(Name = "Tên loại khách hàng: ")]
        [Required(ErrorMessage = "Tên loại khách hàng không được để trống ...")]
        public string NameCateCus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
