//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.Bills = new HashSet<Bill>();
            ImageCoupon = "~/Content/images/Avatar.jpg";
        }
        [Display(Name = "Mã giảm giá: ")]
        [Required(ErrorMessage = "Mã giảm giá không được để trống ...")]
        public string IDCoupon { get; set; }
        [Display(Name = "Tên giảm giá: ")]
        [Required(ErrorMessage = "Tên giảm giá không được để trống ...")]
        public string NameCoupon { get; set; }
        [Display(Name = "Hình ảnh giảm giá: ")]
        public string ImageCoupon { get; set; }
        [Display(Name = "Giá giảm giá: ")]
        [Range(0, 9999999999999999999, ErrorMessage = "Nhập giá lớn hơn 0")]
        [Required(ErrorMessage = "Giá giảm không được để trống ...")]
        public Nullable<double> discount { get; set; }
        [Display(Name = "Mô tả chi tiết:")]
        public string Detail { get; set; }
        [Display(Name = "Ngày bắt đầu: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DateStart { get; set; }
        [Display(Name = "Ngày kết thúc: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DateEnd { get; set; }
        [Display(Name = "Số lượng: ")]
        [Required(ErrorMessage = "Số lượng món ăn không được để trống ...")]
        [Range(0, 9999999999999999999, ErrorMessage = "Nhập số lượng lớn hơn 0")]
        public Nullable<int> Quantity { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
