//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bills = new HashSet<Bill>();
            ImageCustomer = "~/Content/images/Avatar.jpg";
        }

        public int ID { get; set; }
        [Display(Name = "Tài khoản khách hàng:  ")]
        [Required(ErrorMessage = "Tài khoản khách hàng không được để trống ...")]
        public string AccountCustomer { get; set; }
        [Display(Name = "Mật khẩu khách hàng: ")]
        [Required(ErrorMessage = "Mật khẩu khách hàng không được để trống ...")]
        public string PassCustomer { get; set; }
        [Display(Name = "Tên khách hàng: ")]
        [Required(ErrorMessage = "Tên khách hàng không được để trống ...")]
        public string NameCustomer { get; set; }
        [Display(Name = "hình ảnh khách hàng")]
        public string ImageCustomer { get; set; }
        [Display(Name = "Số điện thoại khách hàng: ")]
        [Required(ErrorMessage = "Số điện thoại khách hàng không được để trống ...")]
        [Phone]
        public string PhoneCustomer { get; set; }
        [Display(Name = "Email: ")]
        [Required(ErrorMessage = "Email khách hàng không được để trống ...")]
        [EmailAddress]
        public string EmailCustomer { get; set; }
        [Display(Name = "Ngày sinh khách hàng: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DateOfBirthCustomer { get; set; }
        [Display(Name = "Địa chỉ khách hàng: ")]
        [Required(ErrorMessage = "Địa chỉ khách hàng không được để trống ...")]
        public string AddressCustomer { get; set; }
        [Display(Name = "Giới tính: ")]
        public Nullable<bool> SexCustomer { get; set; }
        [Display(Name = "Điểm tích lũy: ")]
        public Nullable<int> Point { get; set; }
        [Display(Name = "Tên loại khách hàng: ")]
        public string NameCateCustomer { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual CategoryCustomer CategoryCustomer { get; set; }
    }
}
