//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBill
    {
        public int ID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string NameFood { get; set; }
        public Nullable<int> BillName { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Food Food { get; set; }
    }
}
