//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        public Employee()
        {
            ImageEmp = "~/Content/images/Avatar.jpg";
        }
        public int ID { get; set; }
        [Required(ErrorMessage = "Tài khoản nhân viên không được để trống ...")]
        [Display(Name = "Tài khoản nhân viên: ")]
        public string AccountEmp { get; set; }
        [MinLength(6, ErrorMessage = "Mật khẩu phải nhập ít nhất 6 ký tự")]
        [Required(ErrorMessage = "Mật khẩu nhân viên không được để trống ...")]
        [Display(Name = "Mật khẩu nhân viên: ")]
        public string PassEmp { get; set; }
        [Display(Name = "Loại tài khoản: ")]
        public string CateUser { get; set; }
        [Required(ErrorMessage = "Tên nhân viên không được để trống ...")]
        [Display(Name = "Tên nhân viên: ")]
        public string NameEmp { get; set; }
        [Display(Name = "Hình ảnh nhân viên: ")]
        public string ImageEmp { get; set; }
        [Phone]
        [Display(Name = "Số điện thoại nhân viên: ")]
        [Required(ErrorMessage = "số điện thoại nhân viên không được để trống ...")]
        public string PhoneEmp { get; set; }
        [Display(Name = "Email nhân viên: ")]
        [Required(ErrorMessage = "Tên nhân viên không được để trống ...")]
        [EmailAddress]
        public string EmailEmp { get; set; }
        [Display(Name = "Ngày sinh nhân viên: ")]
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DateOfBirthEmp { get; set; }
        [Display(Name = "Địa chỉ nhân viên: ")]
        [Required(ErrorMessage = "Địa chỉ nhân viên không được để trống ...")]
        public string AddressEmp { get; set; }
        [Display(Name = "Giới tính: ")]
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        public Nullable<bool> SexEmp { get; set; }

        public virtual CategoryUser CategoryUser { get; set; }
    }
}
