//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.Web.Mvc;

    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.DetailBills = new HashSet<DetailBill>();
            ImageFood = "~/Content/images/Avatar.jpg";
        }
        [Required(ErrorMessage = "Mã món ăn không được để trống ...")]
        [Display(Name = "Mã món ăn:")]
        public string IDFood { get; set; }
        [Required(ErrorMessage = "Tên món ăn không được để trống ...")]
        [Display(Name = "Tên món ăn:")]
        public string NameFood { get; set; }
        [Display(Name = "Hình ảnh món ăn:")]
        public string ImageFood { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        [Required(ErrorMessage = "Giá món ăn không được để trống ...")]
        [Range(0, 9999999999999999999, ErrorMessage = "Nhập giá lớn hơn 0")]
        [Display(Name = "Giá món ăn: ")]
        public Nullable<double> PriceFood { get; set; }
        [Display(Name = "Trạng thái món ăn: ")]
        public Nullable<bool> StatusFood { get; set; }
        [Display(Name = "Loại món ăn:")]
        public string CateFood { get; set; }
        [Required(ErrorMessage = "Số lượng món ăn không được để trống ...")]
        [Range(0, 9999999999999999999, ErrorMessage = "Nhập số lượng lớn hơn 0")]
        [Display(Name = "Số lượng món ăn:")]
        public Nullable<int> QuantityFood { get; set; }
        [Display(Name = "Mô tả món ăn:")]
        [AllowHtml]
        public string DesFood { get; set; }
        [Display(Name = "Trending:")]
        public string Trending { get; set; }
        
        
    
        public virtual CategoryFood CategoryFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBill> DetailBills { get; set; }
    }
    public enum Gender
    {
        NewFood, BestSeller, Normal
    }
}
